# Generated by Django 5.1.2 on 2024-10-30 15:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import yapa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(yapa.models.yesterday)])),
                ('status', models.IntegerField(choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Critical')], default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completedby', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
